// Copyright (c) 2026 Aristarh Ucolov.
//
// cfgeventspawns.xml parser/writer — the fixed spawn POSITIONS for DayZ central
// economy events (heli crashes, vehicles, contaminated zones, static loot).
// events.xml says what and how many; this file says where. An event with no
// positions here simply never spawns, which is easy to cause by hand and hard
// to see in the raw coordinates — the map editor makes both visible.
//
//	<eventposdef>
//	  <event name="VehicleCivilianSedan">
//	    <zone smin="0" smax="0" dmin="0" dmax="500" r="150"/>   (optional)
//	    <pos x="7886.0" z="8987.6" a="176.0" group="..."/>
//	    ...
//	  </event>
//	</eventposdef>
package types

import (
	"bytes"
	"encoding/xml"
	"os"
	"strings"
)

type SpawnPos struct {
	X     float64 `xml:"x,attr" json:"x"`
	Z     float64 `xml:"z,attr" json:"z"`
	A     float64 `xml:"a,attr" json:"a"`
	Group string  `xml:"group,attr,omitempty" json:"group,omitempty"`
}

// SpawnZone is the optional distance/spawn-count zone some events carry. Kept
// verbatim so a save round-trips it instead of dropping it.
type SpawnZone struct {
	Smin *int `xml:"smin,attr,omitempty" json:"smin,omitempty"`
	Smax *int `xml:"smax,attr,omitempty" json:"smax,omitempty"`
	Dmin *int `xml:"dmin,attr,omitempty" json:"dmin,omitempty"`
	Dmax *int `xml:"dmax,attr,omitempty" json:"dmax,omitempty"`
	R    *int `xml:"r,attr,omitempty"    json:"r,omitempty"`
}

type SpawnEvent struct {
	XMLName xml.Name   `xml:"event" json:"-"`
	Name    string     `xml:"name,attr" json:"name"`
	Zone    *SpawnZone `xml:"zone,omitempty" json:"zone,omitempty"`
	Pos     []SpawnPos `xml:"pos" json:"pos"`
}

type EventSpawnsDoc struct {
	XMLName xml.Name     `xml:"eventposdef" json:"-"`
	Events  []SpawnEvent `xml:"event" json:"events"`
}

func LoadEventSpawns(path string) (*EventSpawnsDoc, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var doc EventSpawnsDoc
	dec := xml.NewDecoder(bytes.NewReader(data))
	dec.Strict = false
	if err := dec.Decode(&doc); err != nil {
		return nil, err
	}
	return &doc, nil
}

// Find returns the event by name (case-insensitive), or nil.
func (d *EventSpawnsDoc) Find(name string) *SpawnEvent {
	for i := range d.Events {
		if strings.EqualFold(d.Events[i].Name, name) {
			return &d.Events[i]
		}
	}
	return nil
}

// SetPositions replaces one event's position list, creating the event if it
// doesn't exist yet. Returns the resulting position count.
func (d *EventSpawnsDoc) SetPositions(name string, pos []SpawnPos) int {
	if e := d.Find(name); e != nil {
		e.Pos = pos
		return len(pos)
	}
	d.Events = append(d.Events, SpawnEvent{Name: name, Pos: pos})
	return len(pos)
}

// SaveEventSpawns writes the document back with an XML header and tab indent.
// Formatting is normalised (this file is machine-generated by BI's tools, so
// there are no hand comments to preserve, unlike types.xml).
func SaveEventSpawns(path string, doc *EventSpawnsDoc) error {
	var buf bytes.Buffer
	buf.WriteString(xml.Header)
	enc := xml.NewEncoder(&buf)
	enc.Indent("", "\t")
	if err := enc.Encode(doc); err != nil {
		return err
	}
	buf.WriteByte('\n')
	// encoding/xml writes empty elements as <pos ...></pos>; vanilla DayZ uses
	// self-closing <pos .../>. Both parse, but match the game's style. pos and
	// zone never carry children, so this is unambiguous.
	out := buf.Bytes()
	out = bytes.ReplaceAll(out, []byte("></pos>"), []byte("/>"))
	out = bytes.ReplaceAll(out, []byte("></zone>"), []byte("/>"))
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, out, 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}
